apiVersion: v1
kind: Service
metadata:
  name: focusflow-web
  namespace: cloudpath
  labels:
    app.kubernetes.io/name: focusflow-web
    app.kubernetes.io/part-of: cloudpath-focusflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: focusflow-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP