apiVersion: apps/v1
kind: Deployment
metadata:
  name: focusflow-web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: focusflow-web
          image: 797989098577.dkr.ecr.ap-south-1.amazonaws.com/cloudpath-focusflow-web-dev:f252371-fix
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
