apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"backend","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"focusflow-api","app.kubernetes.io/part-of":"cloudpath-focusflow","app.kubernetes.io/version":"0.1.0","project":"cloudpath-focusflow"},"name":"focusflow-api","namespace":"cloudpath"},"spec":{"replicas":2,"revisionHistoryLimit":3,"selector":{"matchLabels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"focusflow-api","project":"cloudpath-focusflow"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"focusflow-api","app.kubernetes.io/part-of":"cloudpath-focusflow","app.kubernetes.io/version":"0.1.0","project":"cloudpath-focusflow"}},"spec":{"automountServiceAccountToken":false,"containers":[{"envFrom":[{"configMapRef":{"name":"focusflow-config"}},{"secretRef":{"name":"focusflow-secret"}}],"image":"focusflow-api:0.1.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":15,"periodSeconds":20,"timeoutSeconds":3},"name":"focusflow-api","ports":[{"containerPort":5000,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":5,"periodSeconds":10,"timeoutSeconds":3},"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true},"startupProbe":{"failureThreshold":18,"httpGet":{"path":"/health","port":"http"},"periodSeconds":5},"volumeMounts":[{"mountPath":"/tmp","name":"tmp"}]}],"securityContext":{"fsGroup":1000,"runAsGroup":1000,"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"volumes":[{"emptyDir":{},"name":"tmp"}]}}}}
  creationTimestamp: "2026-08-29T08:59:29Z"
  generation: 11
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: focusflow-api
    app.kubernetes.io/part-of: cloudpath-focusflow
    app.kubernetes.io/version: 0.1.0
    project: cloudpath-focusflow
  name: focusflow-api
  namespace: cloudpath
  resourceVersion: "106180"
  uid: 73bd2ecd-8236-4128-99bc-ba068e1f9610
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: focusflow-api
      project: cloudpath-focusflow
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-09-06T15:59:01+05:30"
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: focusflow-api
        app.kubernetes.io/part-of: cloudpath-focusflow
        app.kubernetes.io/version: 0.1.0
        project: cloudpath-focusflow
    spec:
      automountServiceAccountToken: false
      containers:
      - envFrom:
        - configMapRef:
            name: focusflow-config
        - secretRef:
            name: focusflow-secret
        image: focusflow-api:0.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
        name: focusflow-api
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        startupProbe:
          failureThreshold: 18
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2026-08-29T09:18:50Z"
    lastUpdateTime: "2026-08-29T09:18:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-09-07T08:10:23Z"
    lastUpdateTime: "2026-09-07T08:14:05Z"
    message: ReplicaSet "focusflow-api-cdb9f6587" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 11
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
